spring:
  datasource:
    url: jdbc:mariadb://localhost:3307/cardb
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update

  data:
    rest:
      base-path: /api

  config:
    import: optional:secrets.yml

  #    url: jdbc:h2:mem:testdb

#  jpa:
#    show-sql: true

#  h2:
#    console:
#      enabled: true
#      path: /h2-console

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    enabled: true